spring:
  rabbitmq.addresses: github-rabbitmq:5672
  jpa.hibernate.ddl-auto: none
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-github-analytics/github?autoReconnect=true&useSSL=false
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASSWORD}